name: jekyll_app
type: ruby:2.3
disk: 1024
web:
  locations:
    "/":
      root: "_site"
      index:
        - index.html
      passthru: false
hooks:
  build: |
    gem install bundler
    bundle install
    ALGOLIA_API_KEY='f2199db8ed6ea7fdecbc9439fec2b471' bundle exec jekyll algolia
    bundle exec jekyll build
